on:
  push:
    branches: 
      - master

jobs:
  build:
    name: build & publish to gh-pages
    runs-on: [ubuntu-18.04]
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Build & Deploy to GitHub Pages
        env: 
          BASE_URL: https://guanbinrui.github.io/Maskbook-News/
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        uses: guanbinrui/jekyll-deploy-gh-pages@master
